# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Programmer's Toolkit
email: eddie.summers1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about all things programming and software engineering.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"

# the base hostname & protocol for your site
url: "http://programming.eddie-summers.com"

# Accounts
twitter_username: 
github_username: esummers1
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

# SCSS directory
sass:
  sass_dir: assets/_sass
  style: compressed

# Image directory
images: '/assets/images'
